import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs';


const prisma = new PrismaClient()

async function abc() {

	
 
}


// async function createCities() {
// 	// check if cities already exist
// 	const cities = await prisma.city.findMany()
// 	if (cities.length > 0) return
// 	// create cities
// 	await prisma.city.createMany({
// 		data: [
// 			{ name: "Adana" },
// 			{ name: "Adıyaman" },
// 			{ name: "Afyonkarahisar" },
// 			{ name: "Ağrı" },
// 			{ name: "Amasya" },
// 			{ name: "Ankara" },
// 			{ name: "Antalya" },
// 			{ name: "Artvin" },
// 			{ name: "Aydın" },
// 			{ name: "Balıkesir" },
// 			{ name: "Bilecik" },
// 			{ name: "Bingöl" },
// 			{ name: "Bitlis" },
// 			{ name: "Bolu" },
// 			{ name: "Burdur" },
// 			{ name: "Bursa" },
// 			{ name: "Çanakkale" },
// 			{ name: "Çankırı" },
// 			{ name: "Çorum" },
// 			{ name: "Denizli" },
// 			{ name: "Diyarbakır" },
// 			{ name: "Edirne" },
// 			{ name: "Elazığ" },
// 			{ name: "Erzincan" },
// 			{ name: "Erzurum" },
// 			{ name: "Eskişehir" },
// 			{ name: "Gaziantep" },
// 			{ name: "Giresun" },
// 			{ name: "Gümüşhane" },
// 			{ name: "Hakkari" },
// 			{ name: "Hatay" },
// 			{ name: "Isparta" },
// 			{ name: "Mersin" },
// 			{ name: "İstanbul" },
// 			{ name: "İzmir" },
// 			{ name: "Kars" },
// 			{ name: "Kastamonu" },
// 			{ name: "Kayseri" },
// 			{ name: "Kırklareli" },
// 			{ name: "Kırşehir" },
// 			{ name: "Kocaeli" },
// 			{ name: "Konya" },
// 			{ name: "Kütahya" },
// 			{ name: "Malatya" },
// 			{ name: "Manisa" },
// 			{ name: "Kahramanmaraş" },
// 			{ name: "Mardin" },
// 			{ name: "Muğla" },
// 			{ name: "Muş" },
// 			{ name: "Nevşehir" },
// 			{ name: "Niğde" },
// 			{ name: "Ordu" },
// 			{ name: "Rize" },
// 			{ name: "Sakarya" },
// 			{ name: "Samsun" },
// 			{ name: "Siirt" },
// 			{ name: "Sinop" },
// 			{ name: "Sivas" },
// 			{ name: "Tekirdağ" },
// 			{ name: "Tokat" },
// 			{ name: "Trabzon" },
// 			{ name: "Tunceli" },
// 			{ name: "Şanlıurfa" },
// 			{ name: "Uşak" },
// 			{ name: "Van" },
// 			{ name: "Yozgat" },
// 			{ name: "Zonguldak" },
// 			{ name: "Aksaray" },
// 			{ name: "Bayburt" },
// 			{ name: "Karaman" },
// 			{ name: "Kırıkkale" },
// 			{ name: "Batman" },
// 			{ name: "Şırnak" },
// 			{ name: "Bartın" },
// 			{ name: "Ardahan" },
// 			{ name: "Iğdır" },
// 			{ name: "Yalova" },
// 			{ name: "Karabük" },
// 			{ name: "Kilis" },
// 			{ name: "Osmaniye" },
// 			{ name: "Düzce" },
// 		]
// 	});
// }

// async function createCounties() {
// 	// check if counties already exist
// 	const counties = await prisma.county.findMany()
// 	if (counties.length > 0) return
// 	const cityIds: { [key: string]: string } = {};
// 	const getCityId = async (cityName: string) => {
// 		if (cityIds[cityName]) return cityIds[cityName]
// 		const city = await prisma.city.findFirst({ where: { name: cityName } })
// 		cityIds[cityName] = city!.id
// 		return city!.id;
// 	}
// 	await prisma.county.createMany({
// 		data: [
// 			{ name: "Seyhan", cityId: await getCityId("Adana") },
// 			{ name: "Ceyhan", cityId: await getCityId("Adana") },
// 			{ name: "Feke", cityId: await getCityId("Adana") },
// 			{ name: "Karaisalı", cityId: await getCityId("Adana") },
// 			{ name: "Karataş", cityId: await getCityId("Adana") },
// 			{ name: "Kozan", cityId: await getCityId("Adana") },
// 			{ name: "Pozantı", cityId: await getCityId("Adana") },
// 			{ name: "Saimbeyli", cityId: await getCityId("Adana") },
// 			{ name: "Tufanbeyli", cityId: await getCityId("Adana") },
// 			{ name: "Yumurtalık", cityId: await getCityId("Adana") },
// 			{ name: "Yüreğir", cityId: await getCityId("Adana") },
// 			{ name: "Aladağ", cityId: await getCityId("Adana") },
// 			{ name: "İmamoğlu", cityId: await getCityId("Adana") },
// 			{ name: "Sarıçam", cityId: await getCityId("Adana") },
// 			{ name: "Çukurova", cityId: await getCityId("Adana") },
// 			{ name: "Adıyaman Merkez", cityId: await getCityId("Adıyaman") },
// 			{ name: "Besni", cityId: await getCityId("Adıyaman") },
// 			{ name: "Çelikhan", cityId: await getCityId("Adıyaman") },
// 			{ name: "Gerger", cityId: await getCityId("Adıyaman") },
// 			{ name: "Gölbaşı / Adıyaman", cityId: await getCityId("Adıyaman") },
// 			{ name: "Kahta", cityId: await getCityId("Adıyaman") },
// 			{ name: "Samsat", cityId: await getCityId("Adıyaman") },
// 			{ name: "Sincik", cityId: await getCityId("Adıyaman") },
// 			{ name: "Tut", cityId: await getCityId("Adıyaman") },
// 			{ name: "Afyonkarahisar Merkez", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Bolvadin", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Çay", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Dazkırı", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Dinar", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Emirdağ", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "İhsaniye", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Sandıklı", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Sinanpaşa", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Sultandağı", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Şuhut", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Başmakçı", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Bayat / Afyonkarahisar", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "İscehisar", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Çobanlar", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Evciler", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Hocalar", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Kızılören", cityId: await getCityId("Afyonkarahisar") },
// 			{ name: "Ağrı Merkez", cityId: await getCityId("Ağrı") },
// 			{ name: "Diyadin", cityId: await getCityId("Ağrı") },
// 			{ name: "Doğubayazıt", cityId: await getCityId("Ağrı") },
// 			{ name: "Eleşkirt", cityId: await getCityId("Ağrı") },
// 			{ name: "Hamur", cityId: await getCityId("Ağrı") },
// 			{ name: "Patnos", cityId: await getCityId("Ağrı") },
// 			{ name: "Taşlıçay", cityId: await getCityId("Ağrı") },
// 			{ name: "Tutak", cityId: await getCityId("Ağrı") },
// 			{ name: "Amasya Merkez", cityId: await getCityId("Amasya") },
// 			{ name: "Göynücek", cityId: await getCityId("Amasya") },
// 			{ name: "Gümüşhacıköy", cityId: await getCityId("Amasya") },
// 			{ name: "Merzifon", cityId: await getCityId("Amasya") },
// 			{ name: "Suluova", cityId: await getCityId("Amasya") },
// 			{ name: "Taşova", cityId: await getCityId("Amasya") },
// 			{ name: "Hamamözü", cityId: await getCityId("Amasya") },
// 			{ name: "Altındağ", cityId: await getCityId("Ankara") },
// 			{ name: "Ayaş", cityId: await getCityId("Ankara") },
// 			{ name: "Bala", cityId: await getCityId("Ankara") },
// 			{ name: "Beypazarı", cityId: await getCityId("Ankara") },
// 			{ name: "Çamlıdere", cityId: await getCityId("Ankara") },
// 			{ name: "Çankaya", cityId: await getCityId("Ankara") },
// 			{ name: "Çubuk", cityId: await getCityId("Ankara") },
// 			{ name: "Elmadağ", cityId: await getCityId("Ankara") },
// 			{ name: "Güdül", cityId: await getCityId("Ankara") },
// 			{ name: "Haymana", cityId: await getCityId("Ankara") },
// 			{ name: "Kalecik", cityId: await getCityId("Ankara") },
// 			{ name: "Kızılcahamam", cityId: await getCityId("Ankara") },
// 			{ name: "Nallıhan", cityId: await getCityId("Ankara") },
// 			{ name: "Polatlı", cityId: await getCityId("Ankara") },
// 			{ name: "Şereflikoçhisar", cityId: await getCityId("Ankara") },
// 			{ name: "Yenimahalle", cityId: await getCityId("Ankara") },
// 			{ name: "Gölbaşı / Ankara", cityId: await getCityId("Ankara") },
// 			{ name: "Keçiören", cityId: await getCityId("Ankara") },
// 			{ name: "Mamak", cityId: await getCityId("Ankara") },
// 			{ name: "Sincan", cityId: await getCityId("Ankara") },
// 			{ name: "Kazan", cityId: await getCityId("Ankara") },
// 			{ name: "Akyurt", cityId: await getCityId("Ankara") },
// 			{ name: "Etimesgut", cityId: await getCityId("Ankara") },
// 			{ name: "Evren", cityId: await getCityId("Ankara") },
// 			{ name: "Pursaklar", cityId: await getCityId("Ankara") },
// 			{ name: "Akseki", cityId: await getCityId("Antalya") },
// 			{ name: "Alanya", cityId: await getCityId("Antalya") },
// 			{ name: "Elmalı", cityId: await getCityId("Antalya") },
// 			{ name: "Finike", cityId: await getCityId("Antalya") },
// 			{ name: "Gazipaşa", cityId: await getCityId("Antalya") },
// 			{ name: "Gündoğmuş", cityId: await getCityId("Antalya") },
// 			{ name: "Kaş", cityId: await getCityId("Antalya") },
// 			{ name: "Korkuteli", cityId: await getCityId("Antalya") },
// 			{ name: "Kumluca", cityId: await getCityId("Antalya") },
// 			{ name: "Manavgat", cityId: await getCityId("Antalya") },
// 			{ name: "Serik", cityId: await getCityId("Antalya") },
// 			{ name: "Demre", cityId: await getCityId("Antalya") },
// 			{ name: "İbradı", cityId: await getCityId("Antalya") },
// 			{ name: "Kemer / Antalya", cityId: await getCityId("Antalya") },
// 			{ name: "Aksu / Antalya", cityId: await getCityId("Antalya") },
// 			{ name: "Döşemealtı", cityId: await getCityId("Antalya") },
// 			{ name: "Kepez", cityId: await getCityId("Antalya") },
// 			{ name: "Konyaaltı", cityId: await getCityId("Antalya") },
// 			{ name: "Muratpaşa", cityId: await getCityId("Antalya") },
// 			{ name: "Ardanuç", cityId: await getCityId("Artvin") },
// 			{ name: "Arhavi", cityId: await getCityId("Artvin") },
// 			{ name: "Artvin Merkez", cityId: await getCityId("Artvin") },
// 			{ name: "Borçka", cityId: await getCityId("Artvin") },
// 			{ name: "Hopa", cityId: await getCityId("Artvin") },
// 			{ name: "Şavşat", cityId: await getCityId("Artvin") },
// 			{ name: "Yusufeli", cityId: await getCityId("Artvin") },
// 			{ name: "Murgul", cityId: await getCityId("Artvin") },
// 			{ name: "Bozdoğan", cityId: await getCityId("Aydın") },
// 			{ name: "Çine", cityId: await getCityId("Aydın") },
// 			{ name: "Germencik", cityId: await getCityId("Aydın") },
// 			{ name: "Karacasu", cityId: await getCityId("Aydın") },
// 			{ name: "Koçarlı", cityId: await getCityId("Aydın") },
// 			{ name: "Kuşadası", cityId: await getCityId("Aydın") },
// 			{ name: "Kuyucak", cityId: await getCityId("Aydın") },
// 			{ name: "Nazilli", cityId: await getCityId("Aydın") },
// 			{ name: "Söke", cityId: await getCityId("Aydın") },
// 			{ name: "Sultanhisar", cityId: await getCityId("Aydın") },
// 			{ name: "Yenipazar / Aydın", cityId: await getCityId("Aydın") },
// 			{ name: "Buharkent", cityId: await getCityId("Aydın") },
// 			{ name: "İncirliova", cityId: await getCityId("Aydın") },
// 			{ name: "Karpuzlu", cityId: await getCityId("Aydın") },
// 			{ name: "Köşk", cityId: await getCityId("Aydın") },
// 			{ name: "Didim", cityId: await getCityId("Aydın") },
// 			{ name: "Efeler", cityId: await getCityId("Aydın") },
// 			{ name: "Ayvalık", cityId: await getCityId("Balıkesir") },
// 			{ name: "Balya", cityId: await getCityId("Balıkesir") },
// 			{ name: "Bandırma", cityId: await getCityId("Balıkesir") },
// 			{ name: "Bigadiç", cityId: await getCityId("Balıkesir") },
// 			{ name: "Burhaniye", cityId: await getCityId("Balıkesir") },
// 			{ name: "Dursunbey", cityId: await getCityId("Balıkesir") },
// 			{ name: "Edremit / Balıkesir", cityId: await getCityId("Balıkesir") },
// 			{ name: "Erdek", cityId: await getCityId("Balıkesir") },
// 			{ name: "Gönen / Balıkesir", cityId: await getCityId("Balıkesir") },
// 			{ name: "Havran", cityId: await getCityId("Balıkesir") },
// 			{ name: "İvrindi", cityId: await getCityId("Balıkesir") },
// 			{ name: "Kepsut", cityId: await getCityId("Balıkesir") },
// 			{ name: "Manyas", cityId: await getCityId("Balıkesir") },
// 			{ name: "Savaştepe", cityId: await getCityId("Balıkesir") },
// 			{ name: "Sındırgı", cityId: await getCityId("Balıkesir") },
// 			{ name: "Susurluk", cityId: await getCityId("Balıkesir") },
// 			{ name: "Marmara", cityId: await getCityId("Balıkesir") },
// 			{ name: "Gömeç", cityId: await getCityId("Balıkesir") },
// 			{ name: "Altıeylül", cityId: await getCityId("Balıkesir") },
// 			{ name: "Karesi", cityId: await getCityId("Balıkesir") },
// 			{ name: "Bilecik Merkez", cityId: await getCityId("Bilecik") },
// 			{ name: "Bozüyük", cityId: await getCityId("Bilecik") },
// 			{ name: "Gölpazarı", cityId: await getCityId("Bilecik") },
// 			{ name: "Osmaneli", cityId: await getCityId("Bilecik") },
// 			{ name: "Pazaryeri", cityId: await getCityId("Bilecik") },
// 			{ name: "Söğüt", cityId: await getCityId("Bilecik") },
// 			{ name: "Yenipazar / Bilecik", cityId: await getCityId("Bilecik") },
// 			{ name: "İnhisar", cityId: await getCityId("Bilecik") },
// 			{ name: "Bingöl Merkez", cityId: await getCityId("Bingöl") },
// 			{ name: "Genç", cityId: await getCityId("Bingöl") },
// 			{ name: "Karlıova", cityId: await getCityId("Bingöl") },
// 			{ name: "Kiğı", cityId: await getCityId("Bingöl") },
// 			{ name: "Solhan", cityId: await getCityId("Bingöl") },
// 			{ name: "Adaklı", cityId: await getCityId("Bingöl") },
// 			{ name: "Yayladere", cityId: await getCityId("Bingöl") },
// 			{ name: "Yedisu", cityId: await getCityId("Bingöl") },
// 			{ name: "Adilcevaz", cityId: await getCityId("Bitlis") },
// 			{ name: "Ahlat", cityId: await getCityId("Bitlis") },
// 			{ name: "Bitlis Merkez", cityId: await getCityId("Bitlis") },
// 			{ name: "Hizan", cityId: await getCityId("Bitlis") },
// 			{ name: "Mutki", cityId: await getCityId("Bitlis") },
// 			{ name: "Tatvan", cityId: await getCityId("Bitlis") },
// 			{ name: "Güroymak", cityId: await getCityId("Bitlis") },
// 			{ name: "Bolu Merkez", cityId: await getCityId("Bolu") },
// 			{ name: "Gerede", cityId: await getCityId("Bolu") },
// 			{ name: "Göynük", cityId: await getCityId("Bolu") },
// 			{ name: "Kıbrıscık", cityId: await getCityId("Bolu") },
// 			{ name: "Mengen", cityId: await getCityId("Bolu") },
// 			{ name: "Mudurnu", cityId: await getCityId("Bolu") },
// 			{ name: "Seben", cityId: await getCityId("Bolu") },
// 			{ name: "Dörtdivan", cityId: await getCityId("Bolu") },
// 			{ name: "Yeniçağa", cityId: await getCityId("Bolu") },
// 			{ name: "Ağlasun", cityId: await getCityId("Burdur") },
// 			{ name: "Bucak", cityId: await getCityId("Burdur") },
// 			{ name: "Burdur Merkez", cityId: await getCityId("Burdur") },
// 			{ name: "Gölhisar", cityId: await getCityId("Burdur") },
// 			{ name: "Tefenni", cityId: await getCityId("Burdur") },
// 			{ name: "Yeşilova", cityId: await getCityId("Burdur") },
// 			{ name: "Karamanlı", cityId: await getCityId("Burdur") },
// 			{ name: "Kemer / Burdur", cityId: await getCityId("Burdur") },
// 			{ name: "Altınyayla / Burdur", cityId: await getCityId("Burdur") },
// 			{ name: "Çavdır", cityId: await getCityId("Burdur") },
// 			{ name: "Çeltikçi", cityId: await getCityId("Burdur") },
// 			{ name: "Gemlik", cityId: await getCityId("Bursa") },
// 			{ name: "İnegöl", cityId: await getCityId("Bursa") },
// 			{ name: "İznik", cityId: await getCityId("Bursa") },
// 			{ name: "Karacabey", cityId: await getCityId("Bursa") },
// 			{ name: "Keles", cityId: await getCityId("Bursa") },
// 			{ name: "Mudanya", cityId: await getCityId("Bursa") },
// 			{ name: "Mustafakemalpaşa", cityId: await getCityId("Bursa") },
// 			{ name: "Orhaneli", cityId: await getCityId("Bursa") },
// 			{ name: "Orhangazi", cityId: await getCityId("Bursa") },
// 			{ name: "Yenişehir / Bursa", cityId: await getCityId("Bursa") },
// 			{ name: "Büyükorhan", cityId: await getCityId("Bursa") },
// 			{ name: "Harmancık", cityId: await getCityId("Bursa") },
// 			{ name: "Nilüfer", cityId: await getCityId("Bursa") },
// 			{ name: "Osmangazi", cityId: await getCityId("Bursa") },
// 			{ name: "Yıldırım", cityId: await getCityId("Bursa") },
// 			{ name: "Gürsu", cityId: await getCityId("Bursa") },
// 			{ name: "Kestel", cityId: await getCityId("Bursa") },
// 			{ name: "Ayvacık / Çanakkale", cityId: await getCityId("Çanakkale") },
// 			{ name: "Bayramiç", cityId: await getCityId("Çanakkale") },
// 			{ name: "Biga", cityId: await getCityId("Çanakkale") },
// 			{ name: "Bozcaada", cityId: await getCityId("Çanakkale") },
// 			{ name: "Çan", cityId: await getCityId("Çanakkale") },
// 			{ name: "Çanakkale Merkez", cityId: await getCityId("Çanakkale") },
// 			{ name: "Eceabat", cityId: await getCityId("Çanakkale") },
// 			{ name: "Ezine", cityId: await getCityId("Çanakkale") },
// 			{ name: "Gelibolu", cityId: await getCityId("Çanakkale") },
// 			{ name: "Gökçeada", cityId: await getCityId("Çanakkale") },
// 			{ name: "Lapseki", cityId: await getCityId("Çanakkale") },
// 			{ name: "Yenice / Çanakkale", cityId: await getCityId("Çanakkale") },
// 			{ name: "Çankırı Merkez", cityId: await getCityId("Çankırı") },
// 			{ name: "Çerkeş", cityId: await getCityId("Çankırı") },
// 			{ name: "Eldivan", cityId: await getCityId("Çankırı") },
// 			{ name: "Ilgaz", cityId: await getCityId("Çankırı") },
// 			{ name: "Kurşunlu", cityId: await getCityId("Çankırı") },
// 			{ name: "Orta", cityId: await getCityId("Çankırı") },
// 			{ name: "Şabanözü", cityId: await getCityId("Çankırı") },
// 			{ name: "Yapraklı", cityId: await getCityId("Çankırı") },
// 			{ name: "Atkaracalar", cityId: await getCityId("Çankırı") },
// 			{ name: "Kızılırmak", cityId: await getCityId("Çankırı") },
// 			{ name: "Bayramören", cityId: await getCityId("Çankırı") },
// 			{ name: "Korgun", cityId: await getCityId("Çankırı") },
// 			{ name: "Alaca", cityId: await getCityId("Çorum") },
// 			{ name: "Bayat / Çorum", cityId: await getCityId("Çorum") },
// 			{ name: "Çorum Merkez", cityId: await getCityId("Çorum") },
// 			{ name: "İskilip", cityId: await getCityId("Çorum") },
// 			{ name: "Kargı", cityId: await getCityId("Çorum") },
// 			{ name: "Mecitözü", cityId: await getCityId("Çorum") },
// 			{ name: "Ortaköy / Çorum", cityId: await getCityId("Çorum") },
// 			{ name: "Osmancık", cityId: await getCityId("Çorum") },
// 			{ name: "Sungurlu", cityId: await getCityId("Çorum") },
// 			{ name: "Boğazkale", cityId: await getCityId("Çorum") },
// 			{ name: "Uğurludağ", cityId: await getCityId("Çorum") },
// 			{ name: "Dodurga", cityId: await getCityId("Çorum") },
// 			{ name: "Laçin", cityId: await getCityId("Çorum") },
// 			{ name: "Oğuzlar", cityId: await getCityId("Çorum") },
// 			{ name: "Acıpayam", cityId: await getCityId("Denizli") },
// 			{ name: "Buldan", cityId: await getCityId("Denizli") },
// 			{ name: "Çal", cityId: await getCityId("Denizli") },
// 			{ name: "Çameli", cityId: await getCityId("Denizli") },
// 			{ name: "Çardak", cityId: await getCityId("Denizli") },
// 			{ name: "Çivril", cityId: await getCityId("Denizli") },
// 			{ name: "Güney", cityId: await getCityId("Denizli") },
// 			{ name: "Kale / Denizli", cityId: await getCityId("Denizli") },
// 			{ name: "Sarayköy", cityId: await getCityId("Denizli") },
// 			{ name: "Tavas", cityId: await getCityId("Denizli") },
// 			{ name: "Babadağ", cityId: await getCityId("Denizli") },
// 			{ name: "Bekilli", cityId: await getCityId("Denizli") },
// 			{ name: "Honaz", cityId: await getCityId("Denizli") },
// 			{ name: "Serinhisar", cityId: await getCityId("Denizli") },
// 			{ name: "Pamukkale", cityId: await getCityId("Denizli") },
// 			{ name: "Baklan", cityId: await getCityId("Denizli") },
// 			{ name: "Beyağaç", cityId: await getCityId("Denizli") },
// 			{ name: "Bozkurt / Denizli", cityId: await getCityId("Denizli") },
// 			{ name: "Merkezefendi", cityId: await getCityId("Denizli") },
// 			{ name: "Bismil", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Çermik", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Çınar", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Çüngüş", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Dicle", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Ergani", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Hani", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Hazro", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Kulp", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Lice", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Silvan", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Eğil", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Kocaköy", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Bağlar", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Kayapınar", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Sur", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Yenişehir / Diyarbakır", cityId: await getCityId("Diyarbakır") },
// 			{ name: "Edirne Merkez", cityId: await getCityId("Edirne") },
// 			{ name: "Enez", cityId: await getCityId("Edirne") },
// 			{ name: "Havsa", cityId: await getCityId("Edirne") },
// 			{ name: "İpsala", cityId: await getCityId("Edirne") },
// 			{ name: "Keşan", cityId: await getCityId("Edirne") },
// 			{ name: "Lalapaşa", cityId: await getCityId("Edirne") },
// 			{ name: "Meriç", cityId: await getCityId("Edirne") },
// 			{ name: "Uzunköprü", cityId: await getCityId("Edirne") },
// 			{ name: "Süloğlu", cityId: await getCityId("Edirne") },
// 			{ name: "Ağın", cityId: await getCityId("Elazığ") },
// 			{ name: "Baskil", cityId: await getCityId("Elazığ") },
// 			{ name: "Elazığ Merkez", cityId: await getCityId("Elazığ") },
// 			{ name: "Karakoçan", cityId: await getCityId("Elazığ") },
// 			{ name: "Keban", cityId: await getCityId("Elazığ") },
// 			{ name: "Maden", cityId: await getCityId("Elazığ") },
// 			{ name: "Palu", cityId: await getCityId("Elazığ") },
// 			{ name: "Sivrice", cityId: await getCityId("Elazığ") },
// 			{ name: "Arıcak", cityId: await getCityId("Elazığ") },
// 			{ name: "Kovancılar", cityId: await getCityId("Elazığ") },
// 			{ name: "Alacakaya", cityId: await getCityId("Elazığ") },
// 			{ name: "Çayırlı", cityId: await getCityId("Erzincan") },
// 			{ name: "Erzincan Merkez", cityId: await getCityId("Erzincan") },
// 			{ name: "İliç", cityId: await getCityId("Erzincan") },
// 			{ name: "Kemah", cityId: await getCityId("Erzincan") },
// 			{ name: "Kemaliye", cityId: await getCityId("Erzincan") },
// 			{ name: "Refahiye", cityId: await getCityId("Erzincan") },
// 			{ name: "Tercan", cityId: await getCityId("Erzincan") },
// 			{ name: "Üzümlü", cityId: await getCityId("Erzincan") },
// 			{ name: "Otlukbeli", cityId: await getCityId("Erzincan") },
// 			{ name: "Aşkale", cityId: await getCityId("Erzurum") },
// 			{ name: "Çat", cityId: await getCityId("Erzurum") },
// 			{ name: "Hınıs", cityId: await getCityId("Erzurum") },
// 			{ name: "Horasan", cityId: await getCityId("Erzurum") },
// 			{ name: "İspir", cityId: await getCityId("Erzurum") },
// 			{ name: "Karayazı", cityId: await getCityId("Erzurum") },
// 			{ name: "Narman", cityId: await getCityId("Erzurum") },
// 			{ name: "Oltu", cityId: await getCityId("Erzurum") },
// 			{ name: "Olur", cityId: await getCityId("Erzurum") },
// 			{ name: "Pasinler", cityId: await getCityId("Erzurum") },
// 			{ name: "Şenkaya", cityId: await getCityId("Erzurum") },
// 			{ name: "Tekman", cityId: await getCityId("Erzurum") },
// 			{ name: "Tortum", cityId: await getCityId("Erzurum") },
// 			{ name: "Karaçoban", cityId: await getCityId("Erzurum") },
// 			{ name: "Uzundere", cityId: await getCityId("Erzurum") },
// 			{ name: "Pazaryolu", cityId: await getCityId("Erzurum") },
// 			{ name: "Aziziye", cityId: await getCityId("Erzurum") },
// 			{ name: "Köprüköy", cityId: await getCityId("Erzurum") },
// 			{ name: "Palandöken", cityId: await getCityId("Erzurum") },
// 			{ name: "Yakutiye", cityId: await getCityId("Erzurum") },
// 			{ name: "Çifteler", cityId: await getCityId("Eskişehir") },
// 			{ name: "Mahmudiye", cityId: await getCityId("Eskişehir") },
// 			{ name: "Mihalıççık", cityId: await getCityId("Eskişehir") },
// 			{ name: "Sarıcakaya", cityId: await getCityId("Eskişehir") },
// 			{ name: "Seyitgazi", cityId: await getCityId("Eskişehir") },
// 			{ name: "Sivrihisar", cityId: await getCityId("Eskişehir") },
// 			{ name: "Alpu", cityId: await getCityId("Eskişehir") },
// 			{ name: "Beylikova", cityId: await getCityId("Eskişehir") },
// 			{ name: "İnönü", cityId: await getCityId("Eskişehir") },
// 			{ name: "Günyüzü", cityId: await getCityId("Eskişehir") },
// 			{ name: "Han", cityId: await getCityId("Eskişehir") },
// 			{ name: "Mihalgazi", cityId: await getCityId("Eskişehir") },
// 			{ name: "Odunpazarı", cityId: await getCityId("Eskişehir") },
// 			{ name: "Tepebaşı", cityId: await getCityId("Eskişehir") },
// 			{ name: "Araban", cityId: await getCityId("Gaziantep") },
// 			{ name: "İslahiye", cityId: await getCityId("Gaziantep") },
// 			{ name: "Nizip", cityId: await getCityId("Gaziantep") },
// 			{ name: "Oğuzeli", cityId: await getCityId("Gaziantep") },
// 			{ name: "Yavuzeli", cityId: await getCityId("Gaziantep") },
// 			{ name: "Şahinbey", cityId: await getCityId("Gaziantep") },
// 			{ name: "Şehitkamil", cityId: await getCityId("Gaziantep") },
// 			{ name: "Karkamış", cityId: await getCityId("Gaziantep") },
// 			{ name: "Nurdağı", cityId: await getCityId("Gaziantep") },
// 			{ name: "Alucra", cityId: await getCityId("Giresun") },
// 			{ name: "Bulancak", cityId: await getCityId("Giresun") },
// 			{ name: "Dereli", cityId: await getCityId("Giresun") },
// 			{ name: "Espiye", cityId: await getCityId("Giresun") },
// 			{ name: "Eynesil", cityId: await getCityId("Giresun") },
// 			{ name: "Giresun Merkez", cityId: await getCityId("Giresun") },
// 			{ name: "Görele", cityId: await getCityId("Giresun") },
// 			{ name: "Keşap", cityId: await getCityId("Giresun") },
// 			{ name: "Şebinkarahisar", cityId: await getCityId("Giresun") },
// 			{ name: "Tirebolu", cityId: await getCityId("Giresun") },
// 			{ name: "Piraziz", cityId: await getCityId("Giresun") },
// 			{ name: "Yağlıdere", cityId: await getCityId("Giresun") },
// 			{ name: "Çamoluk", cityId: await getCityId("Giresun") },
// 			{ name: "Çanakçı", cityId: await getCityId("Giresun") },
// 			{ name: "Doğankent", cityId: await getCityId("Giresun") },
// 			{ name: "Güce", cityId: await getCityId("Giresun") },
// 			{ name: "Gümüşhane Merkez", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Kelkit", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Şiran", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Torul", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Köse", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Kürtün", cityId: await getCityId("Gümüşhane") },
// 			{ name: "Çukurca", cityId: await getCityId("Hakkari") },
// 			{ name: "Hakkari Merkez", cityId: await getCityId("Hakkari") },
// 			{ name: "Şemdinli", cityId: await getCityId("Hakkari") },
// 			{ name: "Yüksekova", cityId: await getCityId("Hakkari") },
// 			{ name: "Altınözü", cityId: await getCityId("Hatay") },
// 			{ name: "Dörtyol", cityId: await getCityId("Hatay") },
// 			{ name: "Hassa", cityId: await getCityId("Hatay") },
// 			{ name: "İskenderun", cityId: await getCityId("Hatay") },
// 			{ name: "Kırıkhan", cityId: await getCityId("Hatay") },
// 			{ name: "Reyhanlı", cityId: await getCityId("Hatay") },
// 			{ name: "Samandağ", cityId: await getCityId("Hatay") },
// 			{ name: "Yayladağı", cityId: await getCityId("Hatay") },
// 			{ name: "Erzin", cityId: await getCityId("Hatay") },
// 			{ name: "Belen", cityId: await getCityId("Hatay") },
// 			{ name: "Kumlu", cityId: await getCityId("Hatay") },
// 			{ name: "Antakya", cityId: await getCityId("Hatay") },
// 			{ name: "Arsuz", cityId: await getCityId("Hatay") },
// 			{ name: "Defne", cityId: await getCityId("Hatay") },
// 			{ name: "Payas", cityId: await getCityId("Hatay") },
// 			{ name: "Atabey", cityId: await getCityId("Isparta") },
// 			{ name: "Eğirdir", cityId: await getCityId("Isparta") },
// 			{ name: "Gelendost", cityId: await getCityId("Isparta") },
// 			{ name: "Isparta Merkez", cityId: await getCityId("Isparta") },
// 			{ name: "Keçiborlu", cityId: await getCityId("Isparta") },
// 			{ name: "Senirkent", cityId: await getCityId("Isparta") },
// 			{ name: "Sütçüler", cityId: await getCityId("Isparta") },
// 			{ name: "Şarkikaraağaç", cityId: await getCityId("Isparta") },
// 			{ name: "Uluborlu", cityId: await getCityId("Isparta") },
// 			{ name: "Yalvaç", cityId: await getCityId("Isparta") },
// 			{ name: "Aksu / Isparta", cityId: await getCityId("Isparta") },
// 			{ name: "Gönen / Isparta", cityId: await getCityId("Isparta") },
// 			{ name: "Yenişarbademli", cityId: await getCityId("Isparta") },
// 			{ name: "Anamur", cityId: await getCityId("Mersin") },
// 			{ name: "Erdemli", cityId: await getCityId("Mersin") },
// 			{ name: "Gülnar", cityId: await getCityId("Mersin") },
// 			{ name: "Mut", cityId: await getCityId("Mersin") },
// 			{ name: "Silifke", cityId: await getCityId("Mersin") },
// 			{ name: "Tarsus", cityId: await getCityId("Mersin") },
// 			{ name: "Aydıncık / Mersin", cityId: await getCityId("Mersin") },
// 			{ name: "Bozyazı", cityId: await getCityId("Mersin") },
// 			{ name: "Çamlıyayla", cityId: await getCityId("Mersin") },
// 			{ name: "Akdeniz", cityId: await getCityId("Mersin") },
// 			{ name: "Mezitli", cityId: await getCityId("Mersin") },
// 			{ name: "Toroslar", cityId: await getCityId("Mersin") },
// 			{ name: "Yenişehir / Mersin", cityId: await getCityId("Mersin") },
// 			{ name: "Adalar", cityId: await getCityId("İstanbul") },
// 			{ name: "Bakırköy", cityId: await getCityId("İstanbul") },
// 			{ name: "Beşiktaş", cityId: await getCityId("İstanbul") },
// 			{ name: "Beykoz", cityId: await getCityId("İstanbul") },
// 			{ name: "Beyoğlu", cityId: await getCityId("İstanbul") },
// 			{ name: "Çatalca", cityId: await getCityId("İstanbul") },
// 			{ name: "Eyüp", cityId: await getCityId("İstanbul") },
// 			{ name: "Fatih", cityId: await getCityId("İstanbul") },
// 			{ name: "Gaziosmanpaşa", cityId: await getCityId("İstanbul") },
// 			{ name: "Kadıköy", cityId: await getCityId("İstanbul") },
// 			{ name: "Kartal", cityId: await getCityId("İstanbul") },
// 			{ name: "Sarıyer", cityId: await getCityId("İstanbul") },
// 			{ name: "Silivri", cityId: await getCityId("İstanbul") },
// 			{ name: "Şile", cityId: await getCityId("İstanbul") },
// 			{ name: "Şişli", cityId: await getCityId("İstanbul") },
// 			{ name: "Üsküdar", cityId: await getCityId("İstanbul") },
// 			{ name: "Zeytinburnu", cityId: await getCityId("İstanbul") },
// 			{ name: "Büyükçekmece", cityId: await getCityId("İstanbul") },
// 			{ name: "Kağıthane", cityId: await getCityId("İstanbul") },
// 			{ name: "Küçükçekmece", cityId: await getCityId("İstanbul") },
// 			{ name: "Pendik", cityId: await getCityId("İstanbul") },
// 			{ name: "Ümraniye", cityId: await getCityId("İstanbul") },
// 			{ name: "Bayrampaşa", cityId: await getCityId("İstanbul") },
// 			{ name: "Avcılar", cityId: await getCityId("İstanbul") },
// 			{ name: "Bağcılar", cityId: await getCityId("İstanbul") },
// 			{ name: "Bahçelievler", cityId: await getCityId("İstanbul") },
// 			{ name: "Güngören", cityId: await getCityId("İstanbul") },
// 			{ name: "Maltepe", cityId: await getCityId("İstanbul") },
// 			{ name: "Sultanbeyli", cityId: await getCityId("İstanbul") },
// 			{ name: "Tuzla", cityId: await getCityId("İstanbul") },
// 			{ name: "Esenler", cityId: await getCityId("İstanbul") },
// 			{ name: "Arnavutköy", cityId: await getCityId("İstanbul") },
// 			{ name: "Ataşehir", cityId: await getCityId("İstanbul") },
// 			{ name: "Başakşehir", cityId: await getCityId("İstanbul") },
// 			{ name: "Beylikdüzü", cityId: await getCityId("İstanbul") },
// 			{ name: "Çekmeköy", cityId: await getCityId("İstanbul") },
// 			{ name: "Esenyurt", cityId: await getCityId("İstanbul") },
// 			{ name: "Sancaktepe", cityId: await getCityId("İstanbul") },
// 			{ name: "Sultangazi", cityId: await getCityId("İstanbul") },
// 			{ name: "Aliağa", cityId: await getCityId("İzmir") },
// 			{ name: "Bayındır", cityId: await getCityId("İzmir") },
// 			{ name: "Bergama", cityId: await getCityId("İzmir") },
// 			{ name: "Bornova", cityId: await getCityId("İzmir") },
// 			{ name: "Çeşme", cityId: await getCityId("İzmir") },
// 			{ name: "Dikili", cityId: await getCityId("İzmir") },
// 			{ name: "Foça", cityId: await getCityId("İzmir") },
// 			{ name: "Karaburun", cityId: await getCityId("İzmir") },
// 			{ name: "Karşıyaka", cityId: await getCityId("İzmir") },
// 			{ name: "Kemalpaşa / İzmir", cityId: await getCityId("İzmir") },
// 			{ name: "Kınık", cityId: await getCityId("İzmir") },
// 			{ name: "Kiraz", cityId: await getCityId("İzmir") },
// 			{ name: "Menemen", cityId: await getCityId("İzmir") },
// 			{ name: "Ödemiş", cityId: await getCityId("İzmir") },
// 			{ name: "Seferihisar", cityId: await getCityId("İzmir") },
// 			{ name: "Selçuk", cityId: await getCityId("İzmir") },
// 			{ name: "Tire", cityId: await getCityId("İzmir") },
// 			{ name: "Torbalı", cityId: await getCityId("İzmir") },
// 			{ name: "Urla", cityId: await getCityId("İzmir") },
// 			{ name: "Beydağ", cityId: await getCityId("İzmir") },
// 			{ name: "Buca", cityId: await getCityId("İzmir") },
// 			{ name: "Konak", cityId: await getCityId("İzmir") },
// 			{ name: "Menderes", cityId: await getCityId("İzmir") },
// 			{ name: "Balçova", cityId: await getCityId("İzmir") },
// 			{ name: "Çiğli", cityId: await getCityId("İzmir") },
// 			{ name: "Gaziemir", cityId: await getCityId("İzmir") },
// 			{ name: "Narlıdere", cityId: await getCityId("İzmir") },
// 			{ name: "Güzelbahçe", cityId: await getCityId("İzmir") },
// 			{ name: "Bayraklı", cityId: await getCityId("İzmir") },
// 			{ name: "Karabağlar", cityId: await getCityId("İzmir") },
// 			{ name: "Arpaçay", cityId: await getCityId("Kars") },
// 			{ name: "Digor", cityId: await getCityId("Kars") },
// 			{ name: "Kağızman", cityId: await getCityId("Kars") },
// 			{ name: "Kars Merkez", cityId: await getCityId("Kars") },
// 			{ name: "Sarıkamış", cityId: await getCityId("Kars") },
// 			{ name: "Selim", cityId: await getCityId("Kars") },
// 			{ name: "Susuz", cityId: await getCityId("Kars") },
// 			{ name: "Akyaka", cityId: await getCityId("Kars") },
// 			{ name: "Abana", cityId: await getCityId("Kastamonu") },
// 			{ name: "Araç", cityId: await getCityId("Kastamonu") },
// 			{ name: "Azdavay", cityId: await getCityId("Kastamonu") },
// 			{ name: "Bozkurt / Kastamonu", cityId: await getCityId("Kastamonu") },
// 			{ name: "Cide", cityId: await getCityId("Kastamonu") },
// 			{ name: "Çatalzeytin", cityId: await getCityId("Kastamonu") },
// 			{ name: "Daday", cityId: await getCityId("Kastamonu") },
// 			{ name: "Devrekani", cityId: await getCityId("Kastamonu") },
// 			{ name: "İnebolu", cityId: await getCityId("Kastamonu") },
// 			{ name: "Kastamonu Merkez", cityId: await getCityId("Kastamonu") },
// 			{ name: "Küre", cityId: await getCityId("Kastamonu") },
// 			{ name: "Taşköprü", cityId: await getCityId("Kastamonu") },
// 			{ name: "Tosya", cityId: await getCityId("Kastamonu") },
// 			{ name: "İhsangazi", cityId: await getCityId("Kastamonu") },
// 			{ name: "Pınarbaşı / Kastamonu", cityId: await getCityId("Kastamonu") },
// 			{ name: "Şenpazar", cityId: await getCityId("Kastamonu") },
// 			{ name: "Ağlı", cityId: await getCityId("Kastamonu") },
// 			{ name: "Doğanyurt", cityId: await getCityId("Kastamonu") },
// 			{ name: "Hanönü", cityId: await getCityId("Kastamonu") },
// 			{ name: "Seydiler", cityId: await getCityId("Kastamonu") },
// 			{ name: "Bünyan", cityId: await getCityId("Kayseri") },
// 			{ name: "Develi", cityId: await getCityId("Kayseri") },
// 			{ name: "Felahiye", cityId: await getCityId("Kayseri") },
// 			{ name: "İncesu", cityId: await getCityId("Kayseri") },
// 			{ name: "Pınarbaşı / Kayseri", cityId: await getCityId("Kayseri") },
// 			{ name: "Sarıoğlan", cityId: await getCityId("Kayseri") },
// 			{ name: "Sarız", cityId: await getCityId("Kayseri") },
// 			{ name: "Tomarza", cityId: await getCityId("Kayseri") },
// 			{ name: "Yahyalı", cityId: await getCityId("Kayseri") },
// 			{ name: "Yeşilhisar", cityId: await getCityId("Kayseri") },
// 			{ name: "Akkışla", cityId: await getCityId("Kayseri") },
// 			{ name: "Talas", cityId: await getCityId("Kayseri") },
// 			{ name: "Kocasinan", cityId: await getCityId("Kayseri") },
// 			{ name: "Melikgazi", cityId: await getCityId("Kayseri") },
// 			{ name: "Hacılar", cityId: await getCityId("Kayseri") },
// 			{ name: "Özvatan", cityId: await getCityId("Kayseri") },
// 			{ name: "Babaeski", cityId: await getCityId("Kırklareli") },
// 			{ name: "Demirköy", cityId: await getCityId("Kırklareli") },
// 			{ name: "Kırklareli Merkez", cityId: await getCityId("Kırklareli") },
// 			{ name: "Kofçaz", cityId: await getCityId("Kırklareli") },
// 			{ name: "Lüleburgaz", cityId: await getCityId("Kırklareli") },
// 			{ name: "Pehlivanköy", cityId: await getCityId("Kırklareli") },
// 			{ name: "Pınarhisar", cityId: await getCityId("Kırklareli") },
// 			{ name: "Vize", cityId: await getCityId("Kırklareli") },
// 			{ name: "Çiçekdağı", cityId: await getCityId("Kırşehir") },
// 			{ name: "Kaman", cityId: await getCityId("Kırşehir") },
// 			{ name: "Kırşehir Merkez", cityId: await getCityId("Kırşehir") },
// 			{ name: "Mucur", cityId: await getCityId("Kırşehir") },
// 			{ name: "Akpınar", cityId: await getCityId("Kırşehir") },
// 			{ name: "Akçakent", cityId: await getCityId("Kırşehir") },
// 			{ name: "Boztepe", cityId: await getCityId("Kırşehir") },
// 			{ name: "Gebze", cityId: await getCityId("Kocaeli") },
// 			{ name: "Gölcük", cityId: await getCityId("Kocaeli") },
// 			{ name: "Kandıra", cityId: await getCityId("Kocaeli") },
// 			{ name: "Karamürsel", cityId: await getCityId("Kocaeli") },
// 			{ name: "Körfez", cityId: await getCityId("Kocaeli") },
// 			{ name: "Derince", cityId: await getCityId("Kocaeli") },
// 			{ name: "Başiskele", cityId: await getCityId("Kocaeli") },
// 			{ name: "Çayırova", cityId: await getCityId("Kocaeli") },
// 			{ name: "Darıca", cityId: await getCityId("Kocaeli") },
// 			{ name: "Dilovası", cityId: await getCityId("Kocaeli") },
// 			{ name: "İzmit", cityId: await getCityId("Kocaeli") },
// 			{ name: "Kartepe", cityId: await getCityId("Kocaeli") },
// 			{ name: "Akşehir", cityId: await getCityId("Konya") },
// 			{ name: "Beyşehir", cityId: await getCityId("Konya") },
// 			{ name: "Bozkır", cityId: await getCityId("Konya") },
// 			{ name: "Cihanbeyli", cityId: await getCityId("Konya") },
// 			{ name: "Çumra", cityId: await getCityId("Konya") },
// 			{ name: "Doğanhisar", cityId: await getCityId("Konya") },
// 			{ name: "Ereğli / Konya", cityId: await getCityId("Konya") },
// 			{ name: "Hadim", cityId: await getCityId("Konya") },
// 			{ name: "Ilgın", cityId: await getCityId("Konya") },
// 			{ name: "Kadınhanı", cityId: await getCityId("Konya") },
// 			{ name: "Karapınar", cityId: await getCityId("Konya") },
// 			{ name: "Kulu", cityId: await getCityId("Konya") },
// 			{ name: "Sarayönü", cityId: await getCityId("Konya") },
// 			{ name: "Seydişehir", cityId: await getCityId("Konya") },
// 			{ name: "Yunak", cityId: await getCityId("Konya") },
// 			{ name: "Akören", cityId: await getCityId("Konya") },
// 			{ name: "Altınekin", cityId: await getCityId("Konya") },
// 			{ name: "Derebucak", cityId: await getCityId("Konya") },
// 			{ name: "Hüyük", cityId: await getCityId("Konya") },
// 			{ name: "Karatay", cityId: await getCityId("Konya") },
// 			{ name: "Meram", cityId: await getCityId("Konya") },
// 			{ name: "Selçuklu", cityId: await getCityId("Konya") },
// 			{ name: "Taşkent", cityId: await getCityId("Konya") },
// 			{ name: "Ahırlı", cityId: await getCityId("Konya") },
// 			{ name: "Çeltik", cityId: await getCityId("Konya") },
// 			{ name: "Derbent", cityId: await getCityId("Konya") },
// 			{ name: "Emirgazi", cityId: await getCityId("Konya") },
// 			{ name: "Güneysınır", cityId: await getCityId("Konya") },
// 			{ name: "Halkapınar", cityId: await getCityId("Konya") },
// 			{ name: "Tuzlukçu", cityId: await getCityId("Konya") },
// 			{ name: "Yalıhüyük", cityId: await getCityId("Konya") },
// 			{ name: "Altıntaş", cityId: await getCityId("Kütahya") },
// 			{ name: "Domaniç", cityId: await getCityId("Kütahya") },
// 			{ name: "Emet", cityId: await getCityId("Kütahya") },
// 			{ name: "Gediz", cityId: await getCityId("Kütahya") },
// 			{ name: "Kütahya Merkez", cityId: await getCityId("Kütahya") },
// 			{ name: "Simav", cityId: await getCityId("Kütahya") },
// 			{ name: "Tavşanlı", cityId: await getCityId("Kütahya") },
// 			{ name: "Aslanapa", cityId: await getCityId("Kütahya") },
// 			{ name: "Dumlupınar", cityId: await getCityId("Kütahya") },
// 			{ name: "Hisarcık", cityId: await getCityId("Kütahya") },
// 			{ name: "Şaphane", cityId: await getCityId("Kütahya") },
// 			{ name: "Çavdarhisar", cityId: await getCityId("Kütahya") },
// 			{ name: "Pazarlar", cityId: await getCityId("Kütahya") },
// 			{ name: "Akçadağ", cityId: await getCityId("Malatya") },
// 			{ name: "Arapgir", cityId: await getCityId("Malatya") },
// 			{ name: "Arguvan", cityId: await getCityId("Malatya") },
// 			{ name: "Darende", cityId: await getCityId("Malatya") },
// 			{ name: "Doğanşehir", cityId: await getCityId("Malatya") },
// 			{ name: "Hekimhan", cityId: await getCityId("Malatya") },
// 			{ name: "Pütürge", cityId: await getCityId("Malatya") },
// 			{ name: "Yeşilyurt / Malatya", cityId: await getCityId("Malatya") },
// 			{ name: "Battalgazi", cityId: await getCityId("Malatya") },
// 			{ name: "Doğanyol", cityId: await getCityId("Malatya") },
// 			{ name: "Kale / Malatya", cityId: await getCityId("Malatya") },
// 			{ name: "Kuluncak", cityId: await getCityId("Malatya") },
// 			{ name: "Yazıhan", cityId: await getCityId("Malatya") },
// 			{ name: "Akhisar", cityId: await getCityId("Manisa") },
// 			{ name: "Alaşehir", cityId: await getCityId("Manisa") },
// 			{ name: "Demirci", cityId: await getCityId("Manisa") },
// 			{ name: "Gördes", cityId: await getCityId("Manisa") },
// 			{ name: "Kırkağaç", cityId: await getCityId("Manisa") },
// 			{ name: "Kula", cityId: await getCityId("Manisa") },
// 			{ name: "Salihli", cityId: await getCityId("Manisa") },
// 			{ name: "Sarıgöl", cityId: await getCityId("Manisa") },
// 			{ name: "Saruhanlı", cityId: await getCityId("Manisa") },
// 			{ name: "Selendi", cityId: await getCityId("Manisa") },
// 			{ name: "Soma", cityId: await getCityId("Manisa") },
// 			{ name: "Turgutlu", cityId: await getCityId("Manisa") },
// 			{ name: "Ahmetli", cityId: await getCityId("Manisa") },
// 			{ name: "Gölmarmara", cityId: await getCityId("Manisa") },
// 			{ name: "Köprübaşı / Manisa", cityId: await getCityId("Manisa") },
// 			{ name: "Şehzadeler", cityId: await getCityId("Manisa") },
// 			{ name: "Yunusemre", cityId: await getCityId("Manisa") },
// 			{ name: "Afşin", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Andırın", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Elbistan", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Göksun", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Pazarcık", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Türkoğlu", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Çağlayancerit", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Ekinözü", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Nurhak", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Dulkadiroğlu", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Onikişubat", cityId: await getCityId("Kahramanmaraş") },
// 			{ name: "Derik", cityId: await getCityId("Mardin") },
// 			{ name: "Kızıltepe", cityId: await getCityId("Mardin") },
// 			{ name: "Mazıdağı", cityId: await getCityId("Mardin") },
// 			{ name: "Midyat", cityId: await getCityId("Mardin") },
// 			{ name: "Nusaybin", cityId: await getCityId("Mardin") },
// 			{ name: "Ömerli", cityId: await getCityId("Mardin") },
// 			{ name: "Savur", cityId: await getCityId("Mardin") },
// 			{ name: "Dargeçit", cityId: await getCityId("Mardin") },
// 			{ name: "Yeşilli", cityId: await getCityId("Mardin") },
// 			{ name: "Artuklu", cityId: await getCityId("Mardin") },
// 			{ name: "Bodrum", cityId: await getCityId("Muğla") },
// 			{ name: "Datça", cityId: await getCityId("Muğla") },
// 			{ name: "Fethiye", cityId: await getCityId("Muğla") },
// 			{ name: "Köyceğiz", cityId: await getCityId("Muğla") },
// 			{ name: "Marmaris", cityId: await getCityId("Muğla") },
// 			{ name: "Milas", cityId: await getCityId("Muğla") },
// 			{ name: "Ula", cityId: await getCityId("Muğla") },
// 			{ name: "Yatağan", cityId: await getCityId("Muğla") },
// 			{ name: "Dalaman", cityId: await getCityId("Muğla") },
// 			{ name: "Ortaca", cityId: await getCityId("Muğla") },
// 			{ name: "Kavaklıdere", cityId: await getCityId("Muğla") },
// 			{ name: "Menteşe", cityId: await getCityId("Muğla") },
// 			{ name: "Seydikemer", cityId: await getCityId("Muğla") },
// 			{ name: "Bulanık", cityId: await getCityId("Muş") },
// 			{ name: "Malazgirt", cityId: await getCityId("Muş") },
// 			{ name: "Muş Merkez", cityId: await getCityId("Muş") },
// 			{ name: "Varto", cityId: await getCityId("Muş") },
// 			{ name: "Hasköy", cityId: await getCityId("Muş") },
// 			{ name: "Korkut", cityId: await getCityId("Muş") },
// 			{ name: "Avanos", cityId: await getCityId("Nevşehir") },
// 			{ name: "Derinkuyu", cityId: await getCityId("Nevşehir") },
// 			{ name: "Gülşehir", cityId: await getCityId("Nevşehir") },
// 			{ name: "Hacıbektaş", cityId: await getCityId("Nevşehir") },
// 			{ name: "Kozaklı", cityId: await getCityId("Nevşehir") },
// 			{ name: "Nevşehir Merkez", cityId: await getCityId("Nevşehir") },
// 			{ name: "Ürgüp", cityId: await getCityId("Nevşehir") },
// 			{ name: "Acıgöl", cityId: await getCityId("Nevşehir") },
// 			{ name: "Bor", cityId: await getCityId("Niğde") },
// 			{ name: "Çamardı", cityId: await getCityId("Niğde") },
// 			{ name: "Niğde Merkez", cityId: await getCityId("Niğde") },
// 			{ name: "Ulukışla", cityId: await getCityId("Niğde") },
// 			{ name: "Altunhisar", cityId: await getCityId("Niğde") },
// 			{ name: "Çiftlik", cityId: await getCityId("Niğde") },
// 			{ name: "Akkuş", cityId: await getCityId("Ordu") },
// 			{ name: "Aybastı", cityId: await getCityId("Ordu") },
// 			{ name: "Fatsa", cityId: await getCityId("Ordu") },
// 			{ name: "Gölköy", cityId: await getCityId("Ordu") },
// 			{ name: "Korgan", cityId: await getCityId("Ordu") },
// 			{ name: "Kumru", cityId: await getCityId("Ordu") },
// 			{ name: "Mesudiye", cityId: await getCityId("Ordu") },
// 			{ name: "Perşembe", cityId: await getCityId("Ordu") },
// 			{ name: "Ulubey / Ordu", cityId: await getCityId("Ordu") },
// 			{ name: "Ünye", cityId: await getCityId("Ordu") },
// 			{ name: "Gülyalı", cityId: await getCityId("Ordu") },
// 			{ name: "Gürgentepe", cityId: await getCityId("Ordu") },
// 			{ name: "Çamaş", cityId: await getCityId("Ordu") },
// 			{ name: "Çatalpınar", cityId: await getCityId("Ordu") },
// 			{ name: "Çaybaşı", cityId: await getCityId("Ordu") },
// 			{ name: "İkizce", cityId: await getCityId("Ordu") },
// 			{ name: "Kabadüz", cityId: await getCityId("Ordu") },
// 			{ name: "Kabataş", cityId: await getCityId("Ordu") },
// 			{ name: "Altınordu", cityId: await getCityId("Ordu") },
// 			{ name: "Ardeşen", cityId: await getCityId("Rize") },
// 			{ name: "Çamlıhemşin", cityId: await getCityId("Rize") },
// 			{ name: "Çayeli", cityId: await getCityId("Rize") },
// 			{ name: "Fındıklı", cityId: await getCityId("Rize") },
// 			{ name: "İkizdere", cityId: await getCityId("Rize") },
// 			{ name: "Kalkandere", cityId: await getCityId("Rize") },
// 			{ name: "Pazar / Rize", cityId: await getCityId("Rize") },
// 			{ name: "Rize Merkez", cityId: await getCityId("Rize") },
// 			{ name: "Güneysu", cityId: await getCityId("Rize") },
// 			{ name: "Derepazarı", cityId: await getCityId("Rize") },
// 			{ name: "Hemşin", cityId: await getCityId("Rize") },
// 			{ name: "İyidere", cityId: await getCityId("Rize") },
// 			{ name: "Akyazı", cityId: await getCityId("Sakarya") },
// 			{ name: "Geyve", cityId: await getCityId("Sakarya") },
// 			{ name: "Hendek", cityId: await getCityId("Sakarya") },
// 			{ name: "Karasu", cityId: await getCityId("Sakarya") },
// 			{ name: "Kaynarca", cityId: await getCityId("Sakarya") },
// 			{ name: "Sapanca", cityId: await getCityId("Sakarya") },
// 			{ name: "Kocaali", cityId: await getCityId("Sakarya") },
// 			{ name: "Pamukova", cityId: await getCityId("Sakarya") },
// 			{ name: "Taraklı", cityId: await getCityId("Sakarya") },
// 			{ name: "Ferizli", cityId: await getCityId("Sakarya") },
// 			{ name: "Karapürçek", cityId: await getCityId("Sakarya") },
// 			{ name: "Söğütlü", cityId: await getCityId("Sakarya") },
// 			{ name: "Adapazarı", cityId: await getCityId("Sakarya") },
// 			{ name: "Arifiye", cityId: await getCityId("Sakarya") },
// 			{ name: "Erenler", cityId: await getCityId("Sakarya") },
// 			{ name: "Serdivan", cityId: await getCityId("Sakarya") },
// 			{ name: "Alaçam", cityId: await getCityId("Samsun") },
// 			{ name: "Bafra", cityId: await getCityId("Samsun") },
// 			{ name: "Çarşamba", cityId: await getCityId("Samsun") },
// 			{ name: "Havza", cityId: await getCityId("Samsun") },
// 			{ name: "Kavak", cityId: await getCityId("Samsun") },
// 			{ name: "Ladik", cityId: await getCityId("Samsun") },
// 			{ name: "Terme", cityId: await getCityId("Samsun") },
// 			{ name: "Vezirköprü", cityId: await getCityId("Samsun") },
// 			{ name: "Asarcık", cityId: await getCityId("Samsun") },
// 			{ name: "19 Mayıs", cityId: await getCityId("Samsun") },
// 			{ name: "Salıpazarı", cityId: await getCityId("Samsun") },
// 			{ name: "Tekkeköy", cityId: await getCityId("Samsun") },
// 			{ name: "Ayvacık / Samsun", cityId: await getCityId("Samsun") },
// 			{ name: "Yakakent", cityId: await getCityId("Samsun") },
// 			{ name: "Atakum", cityId: await getCityId("Samsun") },
// 			{ name: "Canik", cityId: await getCityId("Samsun") },
// 			{ name: "İlkadım", cityId: await getCityId("Samsun") },
// 			{ name: "Baykan", cityId: await getCityId("Siirt") },
// 			{ name: "Eruh", cityId: await getCityId("Siirt") },
// 			{ name: "Kurtalan", cityId: await getCityId("Siirt") },
// 			{ name: "Pervari", cityId: await getCityId("Siirt") },
// 			{ name: "Siirt Merkez", cityId: await getCityId("Siirt") },
// 			{ name: "Şirvan", cityId: await getCityId("Siirt") },
// 			{ name: "Tillo", cityId: await getCityId("Siirt") },
// 			{ name: "Ayancık", cityId: await getCityId("Sinop") },
// 			{ name: "Boyabat", cityId: await getCityId("Sinop") },
// 			{ name: "Durağan", cityId: await getCityId("Sinop") },
// 			{ name: "Erfelek", cityId: await getCityId("Sinop") },
// 			{ name: "Gerze", cityId: await getCityId("Sinop") },
// 			{ name: "Sinop Merkez", cityId: await getCityId("Sinop") },
// 			{ name: "Türkeli", cityId: await getCityId("Sinop") },
// 			{ name: "Dikmen", cityId: await getCityId("Sinop") },
// 			{ name: "Saraydüzü", cityId: await getCityId("Sinop") },
// 			{ name: "Divriği", cityId: await getCityId("Sivas") },
// 			{ name: "Gemerek", cityId: await getCityId("Sivas") },
// 			{ name: "Gürün", cityId: await getCityId("Sivas") },
// 			{ name: "Hafik", cityId: await getCityId("Sivas") },
// 			{ name: "İmranlı", cityId: await getCityId("Sivas") },
// 			{ name: "Kangal", cityId: await getCityId("Sivas") },
// 			{ name: "Koyulhisar", cityId: await getCityId("Sivas") },
// 			{ name: "Sivas Merkez", cityId: await getCityId("Sivas") },
// 			{ name: "Suşehri", cityId: await getCityId("Sivas") },
// 			{ name: "Şarkışla", cityId: await getCityId("Sivas") },
// 			{ name: "Yıldızeli", cityId: await getCityId("Sivas") },
// 			{ name: "Zara", cityId: await getCityId("Sivas") },
// 			{ name: "Akıncılar", cityId: await getCityId("Sivas") },
// 			{ name: "Altınyayla / Sivas", cityId: await getCityId("Sivas") },
// 			{ name: "Doğanşar", cityId: await getCityId("Sivas") },
// 			{ name: "Gölova", cityId: await getCityId("Sivas") },
// 			{ name: "Ulaş", cityId: await getCityId("Sivas") },
// 			{ name: "Çerkezköy", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Çorlu", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Hayrabolu", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Malkara", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Muratlı", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Saray / Tekirdağ", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Şarköy", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Marmaraereğlisi", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Ergene", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Kapaklı", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Süleymanpaşa", cityId: await getCityId("Tekirdağ") },
// 			{ name: "Almus", cityId: await getCityId("Tokat") },
// 			{ name: "Artova", cityId: await getCityId("Tokat") },
// 			{ name: "Erbaa", cityId: await getCityId("Tokat") },
// 			{ name: "Niksar", cityId: await getCityId("Tokat") },
// 			{ name: "Reşadiye", cityId: await getCityId("Tokat") },
// 			{ name: "Tokat Merkez", cityId: await getCityId("Tokat") },
// 			{ name: "Turhal", cityId: await getCityId("Tokat") },
// 			{ name: "Zile", cityId: await getCityId("Tokat") },
// 			{ name: "Pazar / Tokat", cityId: await getCityId("Tokat") },
// 			{ name: "Yeşilyurt / Tokat", cityId: await getCityId("Tokat") },
// 			{ name: "Başçiftlik", cityId: await getCityId("Tokat") },
// 			{ name: "Sulusaray", cityId: await getCityId("Tokat") },
// 			{ name: "Akçaabat", cityId: await getCityId("Trabzon") },
// 			{ name: "Araklı", cityId: await getCityId("Trabzon") },
// 			{ name: "Arsin", cityId: await getCityId("Trabzon") },
// 			{ name: "Çaykara", cityId: await getCityId("Trabzon") },
// 			{ name: "Maçka", cityId: await getCityId("Trabzon") },
// 			{ name: "Of", cityId: await getCityId("Trabzon") },
// 			{ name: "Sürmene", cityId: await getCityId("Trabzon") },
// 			{ name: "Tonya", cityId: await getCityId("Trabzon") },
// 			{ name: "Vakfıkebir", cityId: await getCityId("Trabzon") },
// 			{ name: "Yomra", cityId: await getCityId("Trabzon") },
// 			{ name: "Beşikdüzü", cityId: await getCityId("Trabzon") },
// 			{ name: "Şalpazarı", cityId: await getCityId("Trabzon") },
// 			{ name: "Çarşıbaşı", cityId: await getCityId("Trabzon") },
// 			{ name: "Dernekpazarı", cityId: await getCityId("Trabzon") },
// 			{ name: "Düzköy", cityId: await getCityId("Trabzon") },
// 			{ name: "Hayrat", cityId: await getCityId("Trabzon") },
// 			{ name: "Köprübaşı / Trabzon", cityId: await getCityId("Trabzon") },
// 			{ name: "Ortahisar", cityId: await getCityId("Trabzon") },
// 			{ name: "Çemişgezek", cityId: await getCityId("Tunceli") },
// 			{ name: "Hozat", cityId: await getCityId("Tunceli") },
// 			{ name: "Mazgirt", cityId: await getCityId("Tunceli") },
// 			{ name: "Nazımiye", cityId: await getCityId("Tunceli") },
// 			{ name: "Ovacık / Tunceli", cityId: await getCityId("Tunceli") },
// 			{ name: "Pertek", cityId: await getCityId("Tunceli") },
// 			{ name: "Pülümür", cityId: await getCityId("Tunceli") },
// 			{ name: "Tunceli Merkez", cityId: await getCityId("Tunceli") },
// 			{ name: "Akçakale", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Birecik", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Bozova", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Ceylanpınar", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Halfeti", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Hilvan", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Siverek", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Suruç", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Viranşehir", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Harran", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Eyyübiye", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Haliliye", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Karaköprü", cityId: await getCityId("Şanlıurfa") },
// 			{ name: "Banaz", cityId: await getCityId("Uşak") },
// 			{ name: "Eşme", cityId: await getCityId("Uşak") },
// 			{ name: "Karahallı", cityId: await getCityId("Uşak") },
// 			{ name: "Sivaslı", cityId: await getCityId("Uşak") },
// 			{ name: "Ulubey / Uşak", cityId: await getCityId("Uşak") },
// 			{ name: "Uşak Merkez", cityId: await getCityId("Uşak") },
// 			{ name: "Başkale", cityId: await getCityId("Van") },
// 			{ name: "Çatak", cityId: await getCityId("Van") },
// 			{ name: "Erciş", cityId: await getCityId("Van") },
// 			{ name: "Gevaş", cityId: await getCityId("Van") },
// 			{ name: "Gürpınar", cityId: await getCityId("Van") },
// 			{ name: "Muradiye", cityId: await getCityId("Van") },
// 			{ name: "Özalp", cityId: await getCityId("Van") },
// 			{ name: "Bahçesaray", cityId: await getCityId("Van") },
// 			{ name: "Çaldıran", cityId: await getCityId("Van") },
// 			{ name: "Edremit / Van", cityId: await getCityId("Van") },
// 			{ name: "Saray / Van", cityId: await getCityId("Van") },
// 			{ name: "İpekyolu", cityId: await getCityId("Van") },
// 			{ name: "Tuşba", cityId: await getCityId("Van") },
// 			{ name: "Akdağmadeni", cityId: await getCityId("Yozgat") },
// 			{ name: "Boğazlıyan", cityId: await getCityId("Yozgat") },
// 			{ name: "Çayıralan", cityId: await getCityId("Yozgat") },
// 			{ name: "Çekerek", cityId: await getCityId("Yozgat") },
// 			{ name: "Sarıkaya", cityId: await getCityId("Yozgat") },
// 			{ name: "Sorgun", cityId: await getCityId("Yozgat") },
// 			{ name: "Şefaatli", cityId: await getCityId("Yozgat") },
// 			{ name: "Yerköy", cityId: await getCityId("Yozgat") },
// 			{ name: "Yozgat Merkez", cityId: await getCityId("Yozgat") },
// 			{ name: "Aydıncık / Yozgat", cityId: await getCityId("Yozgat") },
// 			{ name: "Çandır", cityId: await getCityId("Yozgat") },
// 			{ name: "Kadışehri", cityId: await getCityId("Yozgat") },
// 			{ name: "Saraykent", cityId: await getCityId("Yozgat") },
// 			{ name: "Yenifakılı", cityId: await getCityId("Yozgat") },
// 			{ name: "Çaycuma", cityId: await getCityId("Zonguldak") },
// 			{ name: "Devrek", cityId: await getCityId("Zonguldak") },
// 			{ name: "Ereğli / Zonguldak", cityId: await getCityId("Zonguldak") },
// 			{ name: "Zonguldak Merkez", cityId: await getCityId("Zonguldak") },
// 			{ name: "Alaplı", cityId: await getCityId("Zonguldak") },
// 			{ name: "Gökçebey", cityId: await getCityId("Zonguldak") },
// 			{ name: "Kilimli", cityId: await getCityId("Zonguldak") },
// 			{ name: "Kozlu", cityId: await getCityId("Zonguldak") },
// 			{ name: "Aksaray Merkez", cityId: await getCityId("Aksaray") },
// 			{ name: "Ortaköy / Aksaray", cityId: await getCityId("Aksaray") },
// 			{ name: "Ağaçören", cityId: await getCityId("Aksaray") },
// 			{ name: "Güzelyurt", cityId: await getCityId("Aksaray") },
// 			{ name: "Sarıyahşi", cityId: await getCityId("Aksaray") },
// 			{ name: "Eskil", cityId: await getCityId("Aksaray") },
// 			{ name: "Gülağaç", cityId: await getCityId("Aksaray") },
// 			{ name: "Bayburt Merkez", cityId: await getCityId("Bayburt") },
// 			{ name: "Aydıntepe", cityId: await getCityId("Bayburt") },
// 			{ name: "Demirözü", cityId: await getCityId("Bayburt") },
// 			{ name: "Ermenek", cityId: await getCityId("Karaman") },
// 			{ name: "Karaman Merkez", cityId: await getCityId("Karaman") },
// 			{ name: "Ayrancı", cityId: await getCityId("Karaman") },
// 			{ name: "Kazımkarabekir", cityId: await getCityId("Karaman") },
// 			{ name: "Başyayla", cityId: await getCityId("Karaman") },
// 			{ name: "Sarıveliler", cityId: await getCityId("Karaman") },
// 			{ name: "Delice", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Keskin", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Kırıkkale Merkez", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Sulakyurt", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Bahşili", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Balışeyh", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Çelebi", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Karakeçili", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Yahşihan", cityId: await getCityId("Kırıkkale") },
// 			{ name: "Batman Merkez", cityId: await getCityId("Batman") },
// 			{ name: "Beşiri", cityId: await getCityId("Batman") },
// 			{ name: "Gercüş", cityId: await getCityId("Batman") },
// 			{ name: "Kozluk", cityId: await getCityId("Batman") },
// 			{ name: "Sason", cityId: await getCityId("Batman") },
// 			{ name: "Hasankeyf", cityId: await getCityId("Batman") },
// 			{ name: "Beytüşşebap", cityId: await getCityId("Şırnak") },
// 			{ name: "Cizre", cityId: await getCityId("Şırnak") },
// 			{ name: "İdil", cityId: await getCityId("Şırnak") },
// 			{ name: "Silopi", cityId: await getCityId("Şırnak") },
// 			{ name: "Şırnak Merkez", cityId: await getCityId("Şırnak") },
// 			{ name: "Uludere", cityId: await getCityId("Şırnak") },
// 			{ name: "Güçlükonak", cityId: await getCityId("Şırnak") },
// 			{ name: "Bartın Merkez", cityId: await getCityId("Bartın") },
// 			{ name: "Kurucaşile", cityId: await getCityId("Bartın") },
// 			{ name: "Ulus", cityId: await getCityId("Bartın") },
// 			{ name: "Amasra", cityId: await getCityId("Bartın") },
// 			{ name: "Ardahan Merkez", cityId: await getCityId("Ardahan") },
// 			{ name: "Çıldır", cityId: await getCityId("Ardahan") },
// 			{ name: "Göle", cityId: await getCityId("Ardahan") },
// 			{ name: "Hanak", cityId: await getCityId("Ardahan") },
// 			{ name: "Posof", cityId: await getCityId("Ardahan") },
// 			{ name: "Damal", cityId: await getCityId("Ardahan") },
// 			{ name: "Aralık", cityId: await getCityId("Iğdır") },
// 			{ name: "Iğdır Merkez", cityId: await getCityId("Iğdır") },
// 			{ name: "Tuzluca", cityId: await getCityId("Iğdır") },
// 			{ name: "Karakoyunlu", cityId: await getCityId("Iğdır") },
// 			{ name: "Yalova Merkez", cityId: await getCityId("Yalova") },
// 			{ name: "Altınova", cityId: await getCityId("Yalova") },
// 			{ name: "Armutlu", cityId: await getCityId("Yalova") },
// 			{ name: "Çınarcık", cityId: await getCityId("Yalova") },
// 			{ name: "Çiftlikköy", cityId: await getCityId("Yalova") },
// 			{ name: "Termal", cityId: await getCityId("Yalova") },
// 			{ name: "Eflani", cityId: await getCityId("Karabük") },
// 			{ name: "Eskipazar", cityId: await getCityId("Karabük") },
// 			{ name: "Karabük Merkez", cityId: await getCityId("Karabük") },
// 			{ name: "Ovacık / Karabük", cityId: await getCityId("Karabük") },
// 			{ name: "Safranbolu", cityId: await getCityId("Karabük") },
// 			{ name: "Yenice / Karabük", cityId: await getCityId("Karabük") },
// 			{ name: "Kilis Merkez", cityId: await getCityId("Kilis") },
// 			{ name: "Elbeyli", cityId: await getCityId("Kilis") },
// 			{ name: "Musabeyli", cityId: await getCityId("Kilis") },
// 			{ name: "Polateli", cityId: await getCityId("Kilis") },
// 			{ name: "Bahçe", cityId: await getCityId("Osmaniye") },
// 			{ name: "Kadirli", cityId: await getCityId("Osmaniye") },
// 			{ name: "Osmaniye Merkez", cityId: await getCityId("Osmaniye") },
// 			{ name: "Düziçi", cityId: await getCityId("Osmaniye") },
// 			{ name: "Hasanbeyli", cityId: await getCityId("Osmaniye") },
// 			{ name: "Sumbas", cityId: await getCityId("Osmaniye") },
// 			{ name: "Toprakkale", cityId: await getCityId("Osmaniye") },
// 			{ name: "Akçakoca", cityId: await getCityId("Düzce") },
// 			{ name: "Düzce Merkez", cityId: await getCityId("Düzce") },
// 			{ name: "Yığılca", cityId: await getCityId("Düzce") },
// 			{ name: "Cumayeri", cityId: await getCityId("Düzce") },
// 			{ name: "Gölyaka", cityId: await getCityId("Düzce") },
// 			{ name: "Çilimli", cityId: await getCityId("Düzce") },
// 			{ name: "Gümüşova", cityId: await getCityId("Düzce") },
// 			{ name: "Kaynaşlı", cityId: await getCityId("Düzce") },
// 		]
// 	})
// }


async function main() {
	// await createCities()
	// await createCounties() 
	await abc()
}
main()
	.then(async () => {
		await prisma.$disconnect()
	})
	.catch(async (e) => {
		console.error(e)
		await prisma.$disconnect()
		process.exit(1)
	})


